name: Deploy Setup Action
description: Download direct tools
inputs:
  solsta_client_id:
    description: Client ID to authenticate usage of Solid State Networks console tools
    required: true
    default: ""
  solsta_client_secret:
    description: Secret Key to authenticate usage of Solid State Networks console tools
    required: true
    default: ""
  console_version:
    description: Version of Solsta Console Tools to use
    required: true
    default: "6.1.2.51"
  scripts_version:
    description: Version of Solsta Deploy Scripts to use
    required: true
    default: "3.7.18"

outputs:
  result:
    description: The state of the action, if processes completed successfully

runs:
  using: composite
  steps:
    - name: Create work directory
      shell: bash
      run: |
        rm -f *.py
        rm -f deploy-scripts-${{ inputs.scripts_version }}.zip
        mkdir -p solsta_work
      
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'
        
    - name: Download deploy scripts
      shell: bash
      run: |
        pip install wget 
        python -m wget -o deploy-scripts-${{ inputs.scripts_version }}.zip https://releases.snxd.com/deploy-scripts-${{ inputs.scripts_version }}.zip
        echo -e "import zipfile\nzip = zipfile.ZipFile('deploy-scripts-${{ inputs.scripts_version }}.zip')\nzip.extractall()\n" > unzip.py
        python unzip.py
      working-directory: solsta_work
      
    - name: Install dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        
    - name: Install python prerequisites
      shell: bash
      run: python -m pip install -r requirements.txt
      working-directory: solsta_work
      
    - name: Write console.json
      shell: bash
      run: |
        # Generate console credential file from env vars
        echo "{\"consoleCredentials\":{\"audience\":\"https://axis.snxd.com/\",\"clientId\":\"${{ inputs.solsta_client_id }}\",\"clientSecret\":\"${{ inputs.solsta_client_secret }}\",\"grant\":\"clientCredentials\",\"scope\":\"d4tv1\"}}"  > client_credentials.json
      working-directory: solsta_work
        
    - name: Cache console tools
      uses: actions/cache@v3
      with:
        path: solsta_work/solsta_console/${{ inputs.console_version }}
        key: direct-${{ inputs.console_version }}
        restore-keys: direct-${{ inputs.console_version }}

    - name: Download Console Tools
      if: runner.os == 'Windows'
      shell: bash
      working-directory: solsta_work
      run: |
        # Download the latest SSN Console Tools if necessary
        if [ ! -d "solsta_console/${{ inputs.console_version }}" ]; then 
          python direct_get.py --overwrite --version="${{ inputs.console_version }}" --target_directory=solsta_console/${{ inputs.console_version }}/ --console_credentials=client_credentials.json --component=console
        fi

branding:
  icon: "download-cloud"
  color: "yellow"
